---
- name: "Install workspace"
  hosts: all 
  become: true
  handlers:
   - include: handlers/handlers.yml
  pre_tasks:
    - name: "Upgrade system apt cache if needed"
      apt:
        update_cache: true
        cache_valid_time: 3600
  roles:
    - baseworkspace
    - php
    - nginx
    - apache

  