---
- name: "nginx install"
  apt:
    name: "nginx"
    state: "latest"
    update_cache: true
  
- name: "Start nginx"
  service:
    name: nginx
    state: started

- name: "Copy config"
  copy:
    src: ../files/site.conf
    dest: /etc/nginx/sites-available/site.conf

- name: "Create symlink"
  file:
    src: /etc/nginx/sites-available/site.conf
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: "Create dir"
  file:
    path: /var/www/site
    state: directory
    mode: '0755'

- name: "Copy content"
  copy:
    src: ~/www/index.php
    dest: /var/www/site/index.php
    mode: '0755'

- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
