---
- name: "nginx install"
  apt:
    name: "nginx"
    state: "latest"
    update_cache: true
  
- name: "Start nginx"
  service:
    name: nginx
    state: started


- name: "Copy config"
  template:
    src: site.conf.j2
    dest: "{{ nginx_path }}/sites-available/site.conf"

- name: "Create symlink"
  file:
    src: "{{ nginx_path }}/sites-available/site.conf"
    dest: "{{ nginx_path }}/sites-enabled/default"
    state: link

- name: "Create dir"
  file:
    path: "{{ site_path }}"
    state: directory
    mode: '0755'

- name: "Copy content"
  copy:
    src: ~/www/index.php
    dest: "{{ site_path }}/index.php"
    mode: '0755'

- name: "Restart nginx"
  service:
    name: nginx
    state: restarted
