---
- name: "apache install"
  apt:
    name: "apache2"
    state: "latest"
    update_cache: true
  
- name: "apache install"
  apt:
    name: "libapache2-mod-php5.6"
    state: "latest"
    update_cache: true
  
- name: "Copy config ports"
  copy:
    src: ../files/ports.conf
    dest: /etc/apache2/ports.conf

- name: "Copy config site"
  copy:
    src: ../files/site.conf
    dest: /etc/apache2/sites-available/site.conf

- name: "Enable module"
  shell: /usr/sbin/a2enmod php5.6

- name: "Enable new site"
  shell: /usr/sbin/a2ensite site.conf

- name: "Disable default Apache site"
  shell: /usr/sbin/a2dissite 000-default.conf

- name: "Start apache"
  service:
    name: apache2
    state: started
