---
- name: "apache install"
  apt:
    name: "apache2"
    state: "latest"
    update_cache: true
  
- name: "apache install"
  apt:
    name: "libapache2-mod-php5.6"
    state: "latest"
    update_cache: true
  
- name: "Copy config ports"
  template:
    src: ports.conf.j2
    dest: "{{ apache_path }}/ports.conf"

- name: "Copy config site"
  template:
    src: site.conf.j2
    dest: "{{ apache_path }}/sites-available/site.conf"

- name: "Enable module"
  shell: /usr/sbin/a2enmod php5.6

- name: "Enable new site"
  shell: /usr/sbin/a2ensite site.conf

- name: "Disable default Apache site"
  shell: /usr/sbin/a2dissite 000-default.conf

- name: "Start apache"
  service:
    name: apache2
    state: started
