---
php_nedded_packages:
  - php5.6-cli
  - php5.6-curl
  - php5.6-fpm
  - php5.6-gd
  - php5.6-intl
  - php5.6-json
  - php5.6-mbstring
  - php5.6-mcrypt
  - php5.6-pdo-mysql
  - php5.6-xml
  - php5.6-zip
